version: '3'

services:
  
  product-launch-db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=d0ck3r_Labs!
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    ports:
      - "4222:4222"
    networks:
      - app-net

  product-launch-web:
    image: <DockerID>/modernize-aspnet-web:v2
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION_STRING=Server=product-launch-db;Database=ProductLaunch;User Id=sa;Password=d0ck3r_Labs!;
    depends_on:
      - product-launch-db
      - message-queue
    networks:
      - app-net

  save-prospect-handler:
    image: <DockerID>/modernize-aspnet-handler:v2
    environment:
      - DB_CONNECTION_STRING=Server=product-launch-db;Database=ProductLaunch;User Id=sa;Password=d0ck3r_Labs!;
    depends_on:
      - product-launch-db
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external: 
     name: nat
